server:
  port: 8081

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: hotel-management-service
  datasource:
    url: jdbc:h2:mem:hoteldb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: TiA+XVEuNl1vL0d9QFJ1RyZqUSEsIg==Zk5LWEtJMklXInF2Y2ZHMnhAejA+JUorJA==IHVrdVVyQ15fRXFwZjVnRV5BJn5XfDE4YQ==VFx0UQ==ey5yYWM=

logging:
  level:
    ru.hotel.hotel: DEBUG
